name: ci

on:
  push:

jobs:
  golden-tests:
    runs-on: ubuntu-latest
    env:
      TECTONIC_VERSION: "0.1.12"
    steps:
      - uses: actions/checkout@v1

      - name: "Install dependencies for Tectonic and script"
        run: |
          sudo apt-get update
          # Tectonic deps
          sudo apt-get install -y --no-install-recommends libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev
          # Test script deps
          sudo apt-get install -y --no-install-recommends poppler-utils comparepdf

      - name: "Run actions/cache@v1: cache tectonic binary"
        uses: actions/cache@v1
        id: cache-tectonic-bin
        with:
          path: ~/.local/bin
          key: cache-tectonic-bin-v1-${{ env.TECTONIC_VERSION }}

      - name: "Build Tectonic"
        if: steps.cache-tectonic-bin.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y --no-install-recommends libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
          sh rustup.sh -y
          cargo install tectonic --version ${{ env.TECTONIC_VERSION }} --root ~/.local/

      - name: "Run actions/cache@v1: cache tectonic cache"
        uses: actions/cache@v1
        id: cache-tectonic-cache
        with:
          path: ~/.cache/Tectonic
          key: cache-tectonic-cache-v1-${{ env.TECTONIC_VERSION }}

      - name: "Prime Tectonic cache"
        if: steps.cache-tectonic-cache.outputs.cache-hit != 'true'
        run: ~/.local/bin/tectonic .github/resources/cacher.tex

      - name: "Run tests"
        run: env PATH=$PATH:~/.local/bin sh test/run-tests.sh
